name: Compile4

on:
  workflow_dispatch:    # Manual trigger

permissions:
  contents: write       # Required for creating releases

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        py: ['tiger']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    
    - name: Get short SHA
      id: short_sha
      run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install .
        pip install pyinstaller onnxruntime

    - name: PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller -c -p ./tigerbx --icon=./tigerbx/exe/ico.ico --add-data "./tigerbx/exe/onnxruntime_providers_shared.dll;onnxruntime/capi" -F ./tigerbx/${{ matrix.py }}.py

    - name: PyInstaller (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller -c -p ./tigerbx --icon=./tigerbx/exe/ico.ico --add-data "./tigerbx/exe/libonnxruntime_providers_shared.so:onnxruntime/capi" -F ./tigerbx/${{ matrix.py }}.py

    - name: PyInstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller -c -p ./tigerbx --icon=./tigerbx/exe/ico.ico --add-data "./tigerbx/exe/libonnxruntime_providers_shared.so:onnxruntime/capi" -F ./tigerbx/${{ matrix.py }}.py

    - name: Package artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release
        copy dist\* release\
        powershell -Command "Compress-Archive -Path release\* -DestinationPath release-${{ matrix.os }}-${{ github.sha }}.zip"

    - name: Package artifacts (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir release
        mv dist/* release/
        zip -r release-${{ matrix.os }}-${{ github.sha}}.zip release/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}-${{ env.SHORT_SHA }}
        path: release-${{ matrix.os }}-${{ env.SHORT_SHA }}.zip

  release:
    needs: build
    if: github.event_name == 'workflow_dispatch'   # Only run on manual trigger
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Draft Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        draft: true
        prerelease: false
        files: |
          artifacts/release-windows-latest-${{ env.SHORT_SHA }}/release-windows-latest-${{ env.SHORT_SHA }}.zip
          artifacts/release-ubuntu-latest-${{ env.SHORT_SHA }}/release-ubuntu-latest-${{ env.SHORT_SHA }}.zip
          artifacts/release-macos-latest-${{ env.SHORT_SHA }}/release-macos-latest-${{ env.SHORT_SHA }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}